import './css/style.css'

import {Inter, Architects_Daughter} from 'next/font/google'

import Header from '@/components/ui/header'

const inter = Inter({
    subsets: ['latin'],
    variable: '--font-inter',
    display: 'swap'
})

const architects_daughter = Architects_Daughter({
    subsets: ['latin'],
    variable: '--font-architects-daughter',
    weight: '400',
    display: 'swap'
})

export const metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
}

export default function RootLayout({
                                       children,
                                   }: {
    children: React.ReactNode
}) {
    return (
        <html lang="en">
        <head>
            <link rel="icon" href="/favicon.ico" type="image/x-icon"/>
        </head>
        <body
            className={`${inter.variable} ${architects_daughter.variable} font-inter antialiased shadow-white text-black tracking-tight scroll-smooth`}>
        <div className="flex flex-col min-h-screen overflow-hidden">
            <Header/>
            {children}
        </div>
        </body>
        </html>
    )
}
 